version: "2.1"
services:
  kubernetes-volume-backup:
    build: .
    volumes:
    - .:/kubernetes-volume-backup
    environment:
      BACKUP_DIRECTORIES: test
      AWS_DEFAULT_REGION: eu-west-1
  test:
    build: .
    command: gradle -t test
    volumes:
    - .:/kubernetes-volume-backup
    - ./mock-serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount/
